import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{ts,tsx,js,jsx}",
    "./components/**/*.{ts,tsx,js,jsx}",
    "./hooks/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Material Design 3 color scheme — dark variant
        "surface-container-lowest":     "#060e20",
        "surface-container-low":        "#131b2e",
        "surface-container":            "#171f33",
        "surface-container-high":       "#222a3d",
        "surface-container-highest":    "#2d3449",
        "surface":                      "#0b1326",
        "surface-dim":                  "#0b1326",
        "surface-bright":               "#31394d",
        "surface-variant":              "#2d3449",
        "surface-tint":                 "#c3c0ff",
        "background":                   "#0b1326",
        "on-background":                "#dae2fd",
        "on-surface":                   "#dae2fd",
        "on-surface-variant":           "#c7c4d8",
        "inverse-surface":              "#dae2fd",
        "inverse-on-surface":           "#283044",
        "outline":                      "#918fa1",
        "outline-variant":              "#464555",
        "primary":                      "#c3c0ff",
        "primary-container":            "#4f46e5",
        "primary-fixed":                "#e2dfff",
        "primary-fixed-dim":            "#c3c0ff",
        "on-primary":                   "#1d00a5",
        "on-primary-container":         "#dad7ff",
        "on-primary-fixed":             "#0f0069",
        "on-primary-fixed-variant":     "#3323cc",
        "inverse-primary":              "#4d44e3",
        "secondary":                    "#d2bbff",
        "secondary-container":          "#6001d1",
        "secondary-fixed":              "#eaddff",
        "secondary-fixed-dim":          "#d2bbff",
        "on-secondary":                 "#3f008e",
        "on-secondary-container":       "#c9aeff",
        "on-secondary-fixed":           "#25005a",
        "on-secondary-fixed-variant":   "#5a00c6",
        "tertiary":                     "#ffb695",
        "tertiary-container":           "#a44100",
        "tertiary-fixed":               "#ffdbcc",
        "tertiary-fixed-dim":           "#ffb695",
        "on-tertiary":                  "#571f00",
        "on-tertiary-container":        "#ffd2be",
        "on-tertiary-fixed":            "#351000",
        "on-tertiary-fixed-variant":    "#7b2f00",
        "error":                        "#ffb4ab",
        "error-container":              "#93000a",
        "on-error":                     "#690005",
        "on-error-container":           "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg:      "0.5rem",
        xl:      "0.75rem",
        full:    "9999px",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body:     ["Inter", "sans-serif"],
        label:    ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
